error fix
error: forrtl: severe (157): Program Exception - access violation
Problem:
writing attempt to the swap array after simulation ended. Indication is status flag of swap array is set to -1.